version: '3'
services:
  mysql:
    image: mysql:5.7
    ports: ['8092:3306']
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=symfony
      - MYSQL_USER=symfony
      - MYSQL_PASSWORD=password
  php:
    build: ./docker/php
    ports: ['8091:9000']
    volumes: ['./symfony/:/var/www/symfony:cached']
  nginx:
    build: ./docker/nginx
    ports: ['8090:80']
    volumes: ['./symfony/:/var/www/symfony:cached']
